[project]
name = "claudia-agent"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Irae Hueck Costa", email = "mail@irae.me" }
]
requires-python = ">=3.13"
dependencies = [
    "llm>=0.31",
    "prompt-toolkit>=3.0.52",
    "pytest>=9.0.3",
    "questionary>=2.1.1",
    "rich>=15.0.0",
]

[project.scripts]
claudia = "claudia:main"

[tool.uv]
package = true
