[project]
name = "claudia-agent"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Irae Hueck Costa", email = "mail@irae.me" }
]
requires-python = ">=3.13"
dependencies = [
    "llm>=0.31",
    "prompt-toolkit>=3.0.52",
    "tqdm>=4.67.3",
]

[project.scripts]
claudia = "claudia:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
